# -*- coding: utf-8 -*-
"""Instagram_OSN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGzu1ddTvZGOPadUKk8y2ZPxOExoNvWy

#Multilingual Instagram Social Network Analysis & Language Classification

This notebook demonstrates a complete data analysis and NLP pipeline on a synthetic Instagram-like dataset containing 500,000 samples across English and 10 Indic languages.

It includes preprocessing, feature extraction, dimensionality reduction, classification, and network visualization.
"""

!nvidia-smi

import torch
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f'GPU is connected: {torch.cuda.get_device_name(0)}')
else:
    device = torch.device('cpu')
    print('GPU NOT AVAILABLE. Please enable GPU in Colab.')

"""## Install Required Libraries"""

!pip install -q transformers datasets evaluate jiwer rouge-score networkx matplotlib seaborn
!pip install -q indic-nlp-library
!pip install -q nltk diff-match-patch asr-evaluation sentencepiece scikit-learn

import json
import random
import datetime
import uuid
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid")

"""## Step 1: Data Extraction (Simulated for 5,00,000 samples across 10 languages)"""

# Define the English + 10 Indic languages
LANGUAGES = ['en', 'te', 'hi', 'ml', 'ta', 'kn', 'mr', 'gu', 'pa', 'or']

LANGUAGE_TEXTS = {
    'en': ["Loving the weather today!", "Just finished a great book.", "Beautiful sunset!", "Delicious meal with friends.", "Working hard today."],
    'hi': ["आज का मौसम बहुत अच्छा है!", "अभी एक बेहतरीन किताब खत्म की।", "सुंदर सूर्यास्त!", "दोस्तों के साथ स्वादिष्ट भोजन।", "आज कड़ी मेहनत कर रहा हूँ।"],
    'te': ["ఈ రోజు వాతావరణం చాలా బాగుంది!", "ఇప్పుడే ఒక గొప్ప పుస్తకం పూర్తి చేసాను.", "అందమైన సూర్యాస్తమయం!", "స్నేహితులతో రుచికరమైన భోజనం.", "ఈ రోజు కష్టపడి పనిచేస్తున్నాను."],
    'ta': ["இன்று வானிலை அருமை!", "ஒரு சிறந்த புத்தகத்தை வாசித்து முடித்தேன்.", "அழகான சூரிய அஸ்தமனம்!", "நண்பர்களுடன் உணவு.", "கடுமையாக உழைக்கிறேன்."],
    'ml': ["ഇന്ന് നല്ല കാലാവസ്ഥയാണ്!", "നല്ലൊരു പുസ്തകം വായിച്ചു.", "മനോഹരമായ സൂര്യാസ്തമയം!", "കൂട്ടുകാരൊത്ത് ഭക്ഷണം.", "കഠിനാധ്വാനം ചെയ്യുന്നു."],
    'kn': ["ಇಂದು ಹವಾಮಾನ ಚೆನ್ನಾಗಿದೆ!", "ಒಂದು ಒಳ್ಳೆಯ ಪುಸ್ತಕ ಓದಿದೆ.", "ಸುಂದರ ಸೂರ್ಯಾಸ್ತ!", "ಸ್ನೇಹಿತರೊಂದಿಗೆ ಊಟ.", "ಕಠಿಣ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದೇನೆ."],
    'mr': ["आज हवामान खूप छान आहे!", "नुकतेच एक उत्तम पुस्तक वाचून पूर्ण केले.", "सुंदर सूर्यास्त!", "मित्रांसोबत जेवण.", "आज खूप काम करत आहे."],
    'gu': ["આજે હવામાન ખૂબ સરસ છે!", "હમણાં જ એક સરસ પુસ્તક વાંચી પૂરી કરી.", "સુંદર સૂર્યાસ્ત!", "મિત્રો સાથે ભોજન.", "આજે સખત કામ કરી રહ્યો છું."],
    'pa': ["ਅੱਜ ਮੌਸਮ ਬਹੁਤ ਵਧੀਆ ਹੈ!", "ਹੁਣੇ ਇੱਕ ਵਧੀਆ ਕਿਤਾਬ ਪੂਰੀ ਕੀਤੀ।", "ਸੁੰਦਰ ਸੂਰਜ ਡੁੱਬਣ!", "ਦੋਸਤਾਂ ਨਾਲ ਖਾਣਾ।", "ਅੱਜ ਸਖਤ ਮਿਹਨਤ ਕਰ ਰਿਹਾ ਹਾਂ।"],
    'or': ["ଆଜି ପାଗ ବହୁତ ଭଲ ଅଛି!", "ବର୍ତ୍ତମାନ ଗୋଟିଏ ଭଲ ବହି ପଢିଲି।", "ସୁନ୍ଦର ସୂର୍ଯ୍ୟାସ୍ତ!", "ସାଙ୍ଗମାନଙ୍କ ସହ ଖାଦ୍ୟ।", "ଆଜି ବହୁତ କାମ କରୁଛି।"]
}

NUM_SAMPLES = 500000
data_records = []

print(f"Starting data extraction/simulation for {NUM_SAMPLES} samples...")
for i in range(NUM_SAMPLES):
    lang = random.choice(LANGUAGES)
    user_id = f"user_{random.randint(1000, 99999)}"

    record = {
        "user_profile": {
            "userid": user_id,
            "user_name": f"user_name_{user_id}",
            "location": random.choice(["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"]),
            "followers": random.randint(10, 100000),
            "following_count": random.randint(10, 1000)
        },
        "content_data": {
            "post_id": str(uuid.uuid4()),
            "text_caption": random.choice(LANGUAGE_TEXTS[lang]) + f" #{lang} #socialmedia",
            "language": lang
        },
        "interaction_data": {
            "tags": [f"@user_{random.randint(1000, 99999)}" for _ in range(random.randint(0, 3))],
            "hashtags": [f"#{lang}", "#instadaily", "#trending"]
        },
        "network_relationship_data": {
            "follow_friend_connection": [f"user_{random.randint(1000, 99999)}" for _ in range(random.randint(0, 5))],
            "suggestions": [f"user_{random.randint(1000, 99999)}" for _ in range(random.randint(0, 5))]
        },
        "engagement_metrics": {
            "no_of_likes_count": random.randint(0, 5000),
            "no_of_comments_count": random.randint(0, 500),
            "no_of_share_counts": random.randint(0, 1000)
        }
    }
    data_records.append(record)

file_name = 'instagram_extracted_data.json'
with open(file_name, 'w', encoding='utf-8') as f:
    json.dump(data_records, f, ensure_ascii=False)

print(f"Successfully extracted and saved {NUM_SAMPLES} samples to {file_name}")

"""## Step 2: Data Loading and Sampling"""

with open('instagram_extracted_data.json', 'r', encoding='utf-8') as f:
    loaded_data = json.load(f)

print(f"Total samples loaded: {len(loaded_data)}")

# Sample subset for rapid demonstration in notebook (first 1000 records) to avoid memory overload
subset_data = loaded_data[:1000]

print("Printing first 2 sample records:\n")
for sample in subset_data[:2]:
    print(json.dumps(sample, indent=2, ensure_ascii=False))
    print("-" * 50)

"""##Step 3: Exploratory Data Analysis"""

print("\n===== EXPLORATORY DATA ANALYSIS (EDA) =====\n")

# Convert JSON → DataFrame (flatten useful fields)
df = pd.DataFrame([{
    "user_id": r["user_profile"]["userid"],
    "location": r["user_profile"]["location"],
    "followers": r["user_profile"]["followers"],
    "following": r["user_profile"]["following_count"],
    "caption": r["content_data"]["text_caption"],
    "language": r["content_data"]["language"],
    "likes": r["engagement_metrics"]["no_of_likes_count"],
    "comments": r["engagement_metrics"]["no_of_comments_count"],
    "shares": r["engagement_metrics"]["no_of_share_counts"]
} for r in subset_data])

# ==============================
# 🔹 1. BASIC INFO
# ==============================
print("Dataset Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nSample Data:\n", df.head())

# ==============================
# 🔹 2. MISSING VALUES
# ==============================
print("\nMissing Values:\n", df.isnull().sum())

# ==============================
# 🔹 3. LANGUAGE DISTRIBUTION
# ==============================
plt.figure(figsize=(10,5))
sns.countplot(data=df, x="language", order=df["language"].value_counts().index)
plt.title("Language Distribution")
plt.show()

# ==============================
# 🔹 4. ENGAGEMENT ANALYSIS
# ==============================
plt.figure(figsize=(10,5))
sns.histplot(df["likes"], bins=30, kde=True)
plt.title("Likes Distribution")
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df["comments"], bins=30, kde=True)
plt.title("Comments Distribution")
plt.show()

# ==============================
# 🔹 5. TOP LOCATIONS
# ==============================
plt.figure(figsize=(10,5))
sns.countplot(data=df, x="location", order=df["location"].value_counts().index)
plt.xticks(rotation=45)
plt.title("Top User Locations")
plt.show()

# ==============================
# 🔹 6. CORRELATION HEATMAP
# ==============================
plt.figure(figsize=(8,6))
sns.heatmap(df[["followers","following","likes","comments","shares"]].corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

# ==============================
# 🔹 7. CAPTION LENGTH ANALYSIS
# ==============================
df["caption_length"] = df["caption"].apply(len)

plt.figure(figsize=(10,5))
sns.histplot(df["caption_length"], bins=30, kde=True)
plt.title("Caption Length Distribution")
plt.show()

"""## Step 4: Visualizations (Before Preprocessing)"""

# Visualization 1: Language Distribution
langs = [r['content_data']['language'] for r in subset_data]
plt.figure(figsize=(10,5))
sns.countplot(x=langs, palette='viridis', order=pd.Series(langs).value_counts().index)
plt.title('Before Preprocessing: Language Distribution')
plt.xlabel('Language')
plt.ylabel('Count')
plt.show()

# Visualization 2: Character Length Distribution Before Preprocessing
original_lengths = [len(r['content_data']['text_caption']) for r in subset_data]
plt.figure(figsize=(10,5))
sns.histplot(original_lengths, bins=20, color='blue', kde=True)
plt.title('Before Preprocessing: Character Length Distribution of Text Captions')
plt.xlabel('Number of Characters')
plt.ylabel('Frequency')
plt.show()

"""## Step 5: Text Preprocessing"""

import re
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

print("Applying Text Preprocessing Pipeline...")

def clean_text(text):
    text = re.sub(r'http\S+', '', text) # Remove URLs
    text = re.sub(r'@\S+', '', text) # Remove mentions
    text = re.sub(r'#\S+', '', text) # Remove hashtags
    text = re.sub(r'[^\w\s]', '', text) # Remove punctuation
    return text.strip()

for item in subset_data:
    original = item["content_data"]["text_caption"]
    cleaned = clean_text(original)
    item["content_data"]["cleaned_caption"] = cleaned

print("Preprocessing complete. Printing first 5 preprocessed text samples:\n")
for sample in subset_data[:5]:
    print("Original:", sample["content_data"]["text_caption"])
    print("Cleaned: ", sample["content_data"]["cleaned_caption"])
    print("-" * 50)

"""## Step 6: Step-by-Step Visualizations (After Preprocessing)"""

# Visualization 3: Character Length Distribution After Preprocessing
cleaned_lengths = [len(r['content_data']['cleaned_caption']) for r in subset_data]
plt.figure(figsize=(10,5))
sns.histplot(cleaned_lengths, bins=20, color='green', kde=True)
plt.title('After Preprocessing: Character Length Distribution of Cleaned Captions')
plt.xlabel('Number of Characters')
plt.ylabel('Frequency')
plt.show()

"""## Step 7: Vectorization (Indic Models - Extracting Embeddings)"""

from transformers import AutoTokenizer, AutoModel
import torch


from sklearn.feature_extraction.text import TfidfVectorizer

print("Applying TF-IDF Vectorization...")

tfidf = TfidfVectorizer(max_features=5000)
tfidf_features = tfidf.fit_transform(sample_texts)

print("TF-IDF Shape:", tfidf_features.shape)

from sklearn.feature_extraction.text import CountVectorizer

print("Applying Bag of Words Vectorization...")

bow = CountVectorizer(max_features=5000)
bow_features = bow.fit_transform(sample_texts)

print("BoW Shape:", bow_features.shape)

model_name = "bert-base-multilingual-cased"
print(f"Loading Simple Multilingual BERT for Vectorization: {model_name}")

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
if torch.cuda.is_available():
    model = model.to('cuda')

total_params = sum(p.numel() for p in model.parameters())
print(f"Total Model parameters: {total_params:,}")
print(f"Model size: {total_params * 4 / (1024**2):.2f} MB")

# Extract text and languages for vectorization
sample_texts = [r["content_data"]["cleaned_caption"] for r in subset_data[:500]]
sample_langs = [r["content_data"]["language"] for r in subset_data[:500]]

print("Applying Vectorization to extract embeddings in batches to prevent Out-Of-Memory (OOM) errors...")
batch_size = 32
all_embeddings = []

model.eval()
with torch.no_grad():
    for i in range(0, len(sample_texts), batch_size):
        batch_texts = sample_texts[i:i+batch_size]
        inputs = tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt", max_length=128)
        if torch.cuda.is_available():
            inputs = {k: v.to('cuda') for k, v in inputs.items()}

        outputs = model(**inputs)
        # Using the mean of the last hidden state as the sentence embedding
        batch_embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
        all_embeddings.extend(batch_embeddings)

embeddings_array = np.array(all_embeddings)
print("Vectorization complete. Extracted Embeddings Array shape:", embeddings_array.shape)
print("Preview of first embedding (first 5 components):", embeddings_array[0][:5])

print("\n--- Feature Comparison ---")
print("TF-IDF Features:", tfidf_features.shape)
print("BoW Features:", bow_features.shape)
print("BERT Embeddings:", embeddings_array.shape)

"""## Step 8: Step-by-Step Visualizations (After Vectorization)"""

# Visualization 4: PCA dimensionality reduction of extracted embeddings
print("Applying PCA to reduce embeddings to 2D for visualization...")
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings_array)

plt.figure(figsize=(10, 8))
sns.scatterplot(x=embeddings_2d[:, 0], y=embeddings_2d[:, 1], hue=sample_langs, palette='tab10', s=100, alpha=0.7)
plt.title('After Vectorization: 2D PCA Projection of IndicBERT Embeddings Colored by Language')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend(title='Language', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

from sklearn.manifold import TSNE

print("Applying t-SNE for dimensionality reduction...")

# Reduce to 2D
tsne = TSNE(n_components=2, perplexity=30, learning_rate=200, random_state=42)
tsne_embeddings = tsne.fit_transform(embeddings_array)

print("t-SNE transformation complete. Shape:", tsne_embeddings.shape)

# Plot
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x=tsne_embeddings[:, 0],
    y=tsne_embeddings[:, 1],
    hue=sample_langs,
    palette='tab10',
    s=100,
    alpha=0.7
)

plt.title("t-SNE Visualization of Text Embeddings (Colored by Language)")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend(title="Language", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""## Step : 9 CLassification Models and Prediction"""

# ================================
# STEP 1: Imports
# ================================
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

# ML Models
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report

# DL Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# ================================
# STEP 2: Prepare Data
# ================================

texts = [r["content_data"]["cleaned_caption"] for r in subset_data[:5000]]
labels = [r["content_data"]["language"] for r in subset_data[:5000]]

# Encode labels
le = LabelEncoder()
y = le.fit_transform(labels)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(texts).toarray()

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data Ready:", X_train.shape)

# ================================
# STEP 3: ML MODELS
# ================================

models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Naive Bayes": MultinomialNB(),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

print("\n===== ML MODELS RESULTS =====\n")

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n🔹 {name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

# ================================
# STEP 4: DEEP LEARNING MODEL
# ================================

print("\n===== DEEP LEARNING MODEL =====\n")

dl_model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(len(le.classes_), activation='softmax')
])

dl_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = dl_model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# Evaluate DL Model
loss, acc = dl_model.evaluate(X_test, y_test)
print("\nDL Model Accuracy:", acc)

# ================================
# STEP 5: TEST WITH NEW INPUT
# ================================

print("\n===== TEST SAMPLE =====\n")

new_text = ["आज मौसम बहुत अच्छा है"]

new_vector = vectorizer.transform(new_text).toarray()

# Test with Random Forest (best usually)
rf_model = models["Random Forest"]
prediction = rf_model.predict(new_vector)

print("Input Text:", new_text[0])
print("Predicted Language:", le.inverse_transform(prediction)[0])

"""## Step 10: Advanced Network Visualization"""

# Visualization 6: Advanced Network Graph Visualization
print("Visualizing Network Graph (User-Friend Connections)...")
G = nx.Graph()

# Add edges for top 50 users to keep graph readable
for record in subset_data[:50]:
    user = record['user_profile']['userid']
    connections = record['network_relationship_data']['follow_friend_connection']
    for friend in connections:
        G.add_edge(user, friend)

plt.figure(figsize=(12, 10))
pos = nx.spring_layout(G, k=0.15)
nx.draw_networkx_nodes(G, pos, node_size=30, node_color='teal', alpha=0.7)
nx.draw_networkx_edges(G, pos, alpha=0.2, edge_color='gray')
plt.title('Network Relationship Graph (Users & Friends)')
plt.axis('off')
plt.show()

print("Building Advanced Social Network Graph...")

G = nx.Graph()

# Build graph
for record in subset_data[:100]:
    user = record['user_profile']['userid']
    connections = record['network_relationship_data']['follow_friend_connection']

    for friend in connections:
        G.add_edge(user, friend)

# Calculate centrality
degree_centrality = nx.degree_centrality(G)

# Get top influencers
top_users = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)[:5]

print("\nTop Influential Users:")
for user, score in top_users:
    print(f"{user} → Centrality Score: {score:.4f}")

plt.figure(figsize=(12, 10))

pos = nx.spring_layout(G, k=0.2)

# Node size based on importance
node_sizes = [v * 2000 for v in degree_centrality.values()]

nx.draw_networkx_nodes(G, pos, node_size=node_sizes, node_color='skyblue', alpha=0.7)
nx.draw_networkx_edges(G, pos, alpha=0.3)

plt.title("Enhanced Social Network Graph (Node size = Influence)")
plt.axis('off')
plt.show()